apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-with-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp-with-http
  template:
    metadata:
      labels:
        app: ftp-with-http
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              find /data -type d -exec chmod 755 {} \; &&
              find /data -type f -exec chmod 644 {} \;
          volumeMounts:
            - name: shared-data
              mountPath: /data

      containers:
        - name: ftp-server
          image: fauria/vsftpd
          env:
            - name: FTP_USER
              value: "testuser"
            - name: FTP_PASS
              value: "testpass"
            - name: PASV_ENABLE
              value: "YES"
            - name: PASV_MIN_PORT
              value: "21100"
            - name: PASV_MAX_PORT
              value: "21100"
            - name: PASV_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LOCAL_UMASK
              value: "022"
          ports:
            - containerPort: 21
            - containerPort: 21100
          volumeMounts:
            - name: shared-data
              mountPath: /home/vsftpd

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: empty-conf
              mountPath: /etc/nginx/conf.d

      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: ftp-data
        - name: nginx-config
          configMap:
            name: nginx-autoindex-config
        - name: empty-conf
          emptyDir: {}
