apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftp-server-chart.fullname" . }}
  labels:
    {{- include "ftp-server-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ftp-server-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: ftp
      protocol: TCP
      port: {{ .Values.service.ports.ftp }}
      targetPort: 21
    - name: pasv
      protocol: TCP
      port: {{ .Values.service.ports.pasv }}
      targetPort: 21100