apiVersion: v1
kind: Service
metadata:
  name: ftp-http-service
spec:
  selector:
    app: ftp-with-http
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: pasv
      port: 21100
      targetPort: 21100
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
